export const SITE = {
  website: "https://blog.kamyk-sklepy.workers.dev/",
  author: "Paweł Kamiński",
  profile: "https://github.com/goodbye-world-dev",
  desc: "Notes on AI agent orchestration — learning in public.",
  title: "Goodbye World",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/goodbye-world-dev/blog/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Warsaw",
} as const;
